### ISSUE TITLE
Pinned articles are also pinned to feeds

### ISSUE THREAD

**Issue by sagamusix** [Shaked/pin_to_top#5]
I don't think it's semantically sensible that pinned articles are also put at the top of article feeds (ATOM, RSS2). I have no idea if this is an architectural issue, but I would prefer the feeds to be sorted chronologically. My use case is that I'm pinning a "welcome" article at the top of my page, but naturally this should not be at the top of the news feed.

**Comment by Shaked** [comment]
@sagamusix - I have stopped using Pelican awhile ago. Feel free to fork this repo

**Comment by sagamusix** [comment]
Fair enough. Maybe put a note in the readme, or ask the plugin to be incorporated into https://github.com/getpelican/pelican-plugins/ ?

Edit: For anyone experiencing the same issue, this problem does not arise when using the "all" variant of the feed.
